### ISSUE TITLE
Dynamic steps

### ISSUE THREAD

**Issue by gauravtiwari** [schneems/wicked#118]
Hi Richard,

I followed your guide on defining dynamic steps however I am getting following error. 

``` ruby
Wicked::Wizard::InvalidStepError - The requested step did not match any steps defined for this controller.:
  wicked (1.0.2) lib/wicked/wizard.rb:58:in `setup_step_from'
  wicked (1.0.2) lib/wicked/wizard.rb:75:in `setup_wizard'
```

The first step seems fine though but all subsequent steps are giving me this error. I am using the same code you have used in your docs for defining dynamic steps. 

Please if you can let me know how to fix this issue. If you need more info please let me know. 

Thank you,
Gaurav

**Comment by kevinjbayer** [comment]
I was just dealing with this issue while using Devise. For me, the cleaner fix was updating after_sign_up_path_for in the Devise RegistrationsController. Using @gauravtiwari's previous example, I originally had:

```
protected
def after_sign_up_path_for(resource)
    after_signup_path(:choose_your_identity)
end
```

It couldn't find the step because of this code always pointing to :choose_your_identity. It started working correctly when I changed this to:

```
protected
  def after_sign_up_path_for(resource)
    if resource.user_type == "Buyer"
      after_signup_path(:choose_your_identity)
    elsif resource.user_type == "Seller"
      after_signup_path(:seller_verification)
    else
      after_signup_path(:seller_verification)
    end
  end
```

Makes sense, it's just not mentioned anywhere else.
