### ISSUE TITLE
next_wizard_path and params

### ISSUE THREAD

**Issue by thorstenhirsch** [schneems/wicked#149]
Hi. Before upgrading to wicked 1.1.0 I could write:
```
redirect_to next_wizard_path(params)
```
But after upgrading this code does not redirect to the next step. Instead it redirects to the same step. It seems like next_wizard_path adopts params[:id] (which contains the current step). I could resolve the problem by deleting :id in params first:
```
params.delete :id
redirect_to next_wizard_path(params)
```
However I don't see any changes in wicked/lib/wicked/controller/concerns/path.rb that might cause the new behaviour. Any ideas?

**Comment by duleorlovic** [comment]
First parameter for [redirect_to](http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to) is a path with eventual params (for example `{my_param: true}` ).
On line [9](https://github.com/duleorlovic/wicked/blob/master/lib/wicked/controller/concerns/render_redirect.rb#L9) 37 and 50, there is `options` parameter that could be used only for flash and status, but not for url params like `path?my_param=true`

Currently I do not see support for those url params since this `options` hash is used for notice, for example [here](https://github.com/schneems/wicked/blob/master/test/dummy/app/controllers/updates_controller.rb#L22)

I would change this options params to take url params. For example [this line 37](https://github.com/duleorlovic/wicked/blob/master/lib/wicked/controller/concerns/render_redirect.rb#L37):
    
    redirect_to wizard_path(next_step), options

should be

    redirect_to wizard_path(next_step, options)


Flash notice could be set inside code `flash[:notice]='blabla'` , no need to pass as params to `render_wizard` .

**Comment by schneems** [comment]
Thanks for the ping! I see now.

You can set options to redirect to using https://github.com/schneems/wicked/pull/136 this is documented in the readme on master. The params will include the `id` and anything you pass into `next_wizard_path` will take precedence in the merge.  

Unfortunately `render_wizard` will perform either a render or a redirect and the interfaces for the two are different, which is why #136 was introduced as the supported way to redirect with parameters.
