### ISSUE TITLE
Way to prevent going back after wizard has finished?

### ISSUE THREAD

**Issue by mockdeep** [schneems/wicked#163]
One thing we're finding our users doing is they will finish the wizard and then click back a few times, at which point the wizard inevitably breaks because they are midway through without the proper setup. One thought that came to mind that would avoid complicated checks is if the url didn't change, so that when they hit back it just goes back to `/my_wizard`. But that would require tracking the step in some other way... Maybe in the session?

**Comment by schneems** [comment]
In my default example the back button should work. Wizards typically work backwards as well as forwards. Think checking out at Amazon, you're freely allowed to go back and change your credit card or home address. If you're going to change the requirements of a wizard, make sure your user understands that they their choices are final and they can't go back, otherwise they may get very frustrated. Though it makes sense that I cannot edit my credit card after submitting an order.

If you wanted to implement this yourself, you could store the current status of the wizard and if someone tries to go back to a section they've already completed, skip ahead to the next section, repeat until the wizard is finished.

**Comment by mockdeep** [comment]
Yeah, we store the current status in the session. There is an order of events our users run through that causes things to fall apart:

1) the user finishes the wizard, at which point we delete the information from the session
2) the user hits back, at which point we redirect them to the start of the wizard and set the session
3) the user hits back some more, at which point everything breaks because there is already info in the session

We could have some logic to check the state of the objects being created, or check the step that they came from and redirect them back, but that seems like a game of cat and mouse, and it would require a complex chain of conditional logic. I think for now we'll just cope with the occasional error that pops up, and look at potentially moving more of the flow to the client side.

One thing that might be nice is to have some sort of state machine/decision tree that could be validated based on where the user came from, either via something stored in the session, or maybe by looking at the request referrer. I guess we can try to write that on our end.
