### ISSUE TITLE
Sending Params to Finish Wizard Path

### ISSUE THREAD

**Issue by Dfenniak** [schneems/wicked#221]
So this was your response to the last time someone asked this question...
<img width="849" alt="how_to_send_params_to_finish_wizard_path_ _issue__198_ _schneems_wicked" src="https://cloud.githubusercontent.com/assets/4259190/19538864/6ebee4de-9613-11e6-9816-17a2f05acff9.png">

Is that just like "No, that's not something I'll do ever" ?

To me it seems super reasonable to pass params during what is effectively a redirect?

**Comment by schneems** [comment]
The problem is the method signature of `render_wizard`, when I wrote wicked I didn't include that as a possibility and instead when you pass a hash into the path it gets passed to `redirect` instead of the actual path. This is good for doing things like using notify (i.e. setting flash). 

We can't easily change the signature without breaking other people's apps. There are several PRs that changed the behavior, but they just straight up removed the old behavior and changed it, no graceful fall-over, no deprecations, no upgrade path...just suddenly your code that was working yesterday isn't working today. 

If you have a current_user, you could store params you want to use in the database and use them in your `finish_wizard_path`


```
def finish_wizard_path
  params = current_user.wizard_params_from_the_database
  user_path(current_user, params)
end
```

It's possible to do it that way.

**Comment by Chocksy** [comment]
@schneems @Dfenniak i made a PR that we are using on our app with the change to allow passing parameters to finish_wizard_path and render_wizard.

**Comment by Dfenniak** [comment]
@schneems I ended up solving this by doing a redirect to the finish path contextually and manually passing the params. definitely not pretty! I appreciate you taking the time to respond, :/ @Chocksy thanks for making the PR man!

**Comment by Chocksy** [comment]
@Dfenniak no problem let's see if @schneems likes what i did there and if so i can update the readme with an example of how it would work.
