### ISSUE TITLE
[Documentation Issue] can you expand on the 'building partial objects step by step' documentation?

### ISSUE THREAD

**Issue by conwayanderson** [schneems/wicked#234]
I'm trying to use the Wicked gem to handle the entire creation of an object. Is there a more thorough end to end tutorial, including the view-logic, related to [this Wiki page](https://github.com/schneems/wicked/wiki/Building-Partial-Objects-Step-by-Step)?

**Comment by schneems** [comment]
That's all I got.

**Comment by conwayanderson** [comment]
Okay, I take it from that response that you're not interested in expanding on this in the future either? In particular, I'm not sure what implementation you're envisioning exactly for "or we can use a route with a placeholder product_id such as [POST] /products/building/build in order to hit this create action."

**Comment by schneems** [comment]
Nope. I don't use wicked that way anymore so I don't have any examples to go off of. You can check out the tests directory, they're all examples of how you can write controllers and that can help. I wrote that wiki years ago and haven't touched it since.

If you want to write a tutorial I'll be happy to link to it and tweet about it.
