### ISSUE TITLE
Get a specific controller's wizard steps

### ISSUE THREAD

**Issue by itmart** [schneems/wicked#246]
I have two wizard controllers right now. Let's say one of them looks like this:

```
class MyController < ApplicationController

  include Wicked::Wizard

  steps :wash, :rinse, :dry
```

I'm in a model and want to access the steps in `MyController`, is there a way to? I've tried `MyController.new.wizard_steps`, `MyController.steps`, `MyController::wizard_steps` but nothing seems to work.

**Comment by schneems** [comment]
The best way i've seen is to define them in a constant somewhere

```
class MyController < ApplicationController
  MY_STEPS = [:wash, :rinse, :dry]
  include Wicked::Wizard

  steps MY_STEPS
```

Then you can access it via `MyController::MY_STEPS`.

**Comment by jdudley1123** [comment]
This doesn't seem to work anymore.

I get an error "The requested step did not match any steps defined for this controller" thrown by [`wizard.rb:66`](https://github.com/zombocom/wicked/blob/2e7114d7027d71b9a10c7d8eee78717cc3e617d6/lib/wicked/wizard.rb#L66).

I think it's because the format of the steps has changed. The `valid_steps` variable (`valid_steps = steps + self.class::PROTECTED_STEPS`) returns `[[:wash, :rinse, :dry], "wicked_finish", "wicked_first", "wicked_last"]`, so it looks like we've got an array within an array rather than the the protected steps being added to the existing steps array.

The addition of a splat operator solves the problem
```ruby
class MyController < ApplicationController
  MY_STEPS = [:wash, :rinse, :dry]
  include Wicked::Wizard

  steps *MY_STEPS
```

**Comment by written-fresh** [comment]
@jdudley1123 thanks for this comment, I was looking around to see if I could find a way to skip all the way to the end of my stepper and couldn't find docs for it.

e.g. be on the wash step and have a skip button to skip all next steps

```
<%= link_to 'Skip', wizard_path("wicked_finish") %>
```
