### ISSUE TITLE
uninitialized constant Wicked::Wizard

### ISSUE THREAD

**Issue by JakeAustwick** [schneems/wicked#3]
Getting the following error when using a namespaced controller.

uninitialized constant Wicked::Wizard

The following makes no difference either:
::Wicked::Wizard

**Comment by fbshah** [comment]
New to Ruby on Rails, unsure on how to integrate the Wicked gem with Devise. 
I am using the confirmable module, which sends an email to confirm account after inserting email and password. 

How do I enable Devise to confirm after all the registrations steps are completed rather than after the initial sign up page?
